async_mode: threaded
cache:
  type: none
chunks:
  group_by_columns:
  - id
  overlap: 100
  size: 1200
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 1
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_reports:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    model: text-embedding-3-small
    type: openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 1
  prompt: prompts/entity_extraction.txt
global_search: null
input:
  base_dir: input/test/words
  file_encoding: utf-8
  file_pattern: ^.*book_part_11\.txt$
  file_type: text
  type: file
llm:
  api_key: ${GRAPHRAG_API_KEY}
  model: gpt-3.5-turbo
  model_supports_json: true
  type: openai_chat
local_search: null
parallelization:
  stagger: 0.3
reporting:
  base_dir: output/book_session_41/reports
  type: file
skip_workflows:
- create_base_text_units
snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false
storage:
  base_dir: output/book_session_41/artifacts
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
